# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-12 11:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('confess', '0002_auto_20170209_1210'),
    ]

    operations = [
        migrations.AddField(
            model_name='confession',
            name='comment_no',
            field=models.IntegerField(default=0),
        ),
    ]
