# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-14 18:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        ('confess', '0007_auto_20170313_2348'),
    ]

    operations = [
        migrations.AddField(
            model_name='confession',
            name='host_group',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='auth.Group'),
            preserve_default=False,
        ),
    ]
