# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-24 09:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('confess', '0014_remove_confession_comment_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='confession',
            name='comment_count',
            field=models.IntegerField(default=0),
        ),
    ]
